### ISSUE TITLE
Hask key không tương thích với file aab

### ISSUE THREAD

**Issue by payment27062022** [tiendung01023/zalo_flutter#10]
Hiện tại ứng dụng của mình có tích hợp phần đăng nhập thông qua Zalo và đang bị lỗi như sau:

Trường hợp 1 (Ứng dụng được build ra file apk dạng debug): Hash key tương ứng bản build ra file apk dạng debug thì thực hiện đăng nhập thành công

Trường hợp 2 (Ứng dụng được build ra file apk dạng release có dùng keystore): Hash key tương ứng bản build ra file apk dạng release thì thực hiện đăng nhập thành công

Trường hợp 3 (Ứng dụng được build ra file aab có dùng keystore và đã upload lên CHPlay): Hash key tương ứng bản build ra file aab thì thực hiện đăng nhập không thành công và báo lỗi ("error_name":"Invalid android sign key","error_reason":"Hash key is invalid","ref_doc":"https://developers.zalo.me/docs/api/social-api/tham-khao/user-access-token-post-4316","error_description":"Invalid android sign key")

Trường hợp 4: các thiết bị Android 13 là tất cả đều không thực hiện được đăng nhập bằng Zalo. Android 12 trở xuống thì sẽ gặp như Trường hợp 1, 2 và 3

Cho mình hỏi là hiện tại phần tạo Hash key này chỉ có hiệu lực trên các file apk hay sao, còn file aab thì thế nào có cách nào khác để tạo Hash key phù hợp với bản build dạng file aab không. Giữa cách tạo Hash key cho file apk và file aab có gì khác không?

Đang sử dụng thư viện phiên bản (zalo_flutter 0.0.5) https://pub.dev/packages/zalo_flutter

Rất mong được hổ trợ gấp phần này.

**Comment by tiendung01023** [comment]
@payment27062022 Xin lỗi bạn vì mình phản hồi chậm trễ. 
Trường hợp 1-3: Mình có thử tái hiện lại đưa file aab lên store thì do file aab được store ký lại nên mã hashKey nó khác đi. Bạn tạo 1 tính năng ẩn trong bản aab để lấy hashKey mới, gắn vào ZaloDeveloper nha.
Trường hợp 4: Mình đang chưa có máy để test nên chưa tái hiện được, để mình kiếm máy check thử. Mà bị ngay cả khi debug luôn hả bạn

**Comment by namminh** [comment]
hi bạn còn hỗ trợ tích hợp không, mình lấy được hashkey tuy nhiêu bị lỗi khi đăng nhập:
V/zalo_flutter(18358): HashKey ANDROID. Copy it to Dashboard [https://developers.zalo.me/app/{your_app_id}/login]
V/zalo_flutter(18358): oCOk7LTdX0QCSJTu4hV4Fh1eBmg=
V/zalo_flutter(18358): ------------------------------------------------------------------------------------------------
[log] HashKey: oCOk7LTdX0QCSJTu4hV4Fh1eBmg=
I/flutter (18358): [2023-08-28 15:52:17.071747][commonButton] login
I/flutter (18358): login: null
Bạn hỗ trợ nhé

**Comment by tiendung01023** [comment]
Chào bạn @namminh,
Bạn đã gắn hashkey vào zalo dashboard chưa nhỉ?

**Comment by tiendung01023** [comment]
@namminh Bạn kiểm tra lại bước 1.4.2 theo như document giúp mình đã sửa android:name=".MyApplication" chưa nha
Bug ban đầu mình đã fix ở bản cập nhật 0.0.6. Mình xin phép đóng ticket này. Nếu vẫn còn bị lỗi mọi người reopen lại nhé
