### ISSUE TITLE
Android14 bị báo lỗi Bản zalo hiện tại không tương thích! mặc dù đã cập nhật bản mới nhất 

### ISSUE THREAD

**Issue by hieumt211299** [tiendung01023/zalo_flutter#13]
Mình đang gặp lỗi không thể mở zalo trên android14 (những bản khác chạy bình thường).

Khi code chạy tới đây
 Map<dynamic, dynamic> res = await ZaloFlutter.login(
      refreshToken: refreshToken,
    );
Show thông báo Zalo hiện tại không tương thích :
    
    
DEBUG CONSOLE: 
D/ScrollerOptimizationManager( 6666): registerConfigChangedListener
W/libc    ( 6666): Access denied finding property "ro.vendor.display.iris_x7.support"
D/VRI[MainActivity]( 6666): hardware acceleration = true, forceHwAccelerated = false
D/BufferQueueConsumer( 6666): [](id:1a0a0000000b,api:0,p:-1,c:6666) connect: controlledByApp=false
E/OpenGLRenderer( 6666): Unable to match the desired swap behavior.
D/VRI[MainActivity]( 6666): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4376 android.view.ViewRootImpl.doTraversal:2992 android.view.ViewRootImpl$TraversalRunnable.run:10469 android.view.Choreographer$CallbackRecord.run:1671 android.view.Choreographer$CallbackRecord.run:1680
D/VRI[MainActivity]( 6666): vri.Setup new sync=wmsSync-VRI[MainActivity]#22
D/OpenGLRenderer( 6666): makeCurrent grContext:0xb40000779037c4e0 reset mTextureAvailable
D/BLASTBufferQueue( 6666): [VRI[MainActivity]#11](f:0,a:1) acquireNextBufferLocked size=973x388 mFrameNumber=1 applyTransaction=true mTimestamp=1476429047394385(auto) mPendingTransactions.size=0 graphicBufferId=28630251995207 transform=0
D/VRI[MainActivity]( 6666): vri.reportDrawFinished

**Comment by hieumt211299** [comment]
![z5374518266675_d156d194db8ffe030bb5b0ce0d595dfc](https://github.com/tiendung01023/zalo_flutter/assets/115162625/e146ae17-deea-4ae3-b177-628de6e4eca4)

**Comment by tiendung01023** [comment]
Bản cập nhật tiếp theo sẽ fix lỗi này ạ, đợt này mình khá bận nên chưa có thời gian support mọi người fix sớm. Có gì mn support giúp mình PR với nha
