### ISSUE TITLE
Unresolved reference: ZaloSDK in 0.0.7

### ISSUE THREAD

**Issue by azhezzzz** [tiendung01023/zalo_flutter#16]
it works good at version 0.0.6 but when i upgrade to 0.0.7 it was wrong with 
`
zalo_flutter-master/example/android/app/src/main/kotlin/com/tiendung01023/example/MainActivity.kt: (5, 36): Unresolved reference: ZaloSDK
`

`
zalo_flutter-master/example/android/app/src/main/kotlin/com/tiendung01023/example/MyApplication.kt: (5, 36): Unresolved reference: ZaloSDKApplication
`
<img width="578" alt="image" src="https://github.com/user-attachments/assets/61ba975f-ca10-4663-9cc4-0fcba826c59f">

**Comment by tiendung01023** [comment]
Did you call `flutter clean`? @azhezzzz

**Comment by azhezzzz** [comment]
Yes, i try it and reinstall the dependencies but still not work.
My flutter version is 3.24.3.
Can you upgrade the zalo_flutter version of this project example  to latest(0.0.7) and check if run it successfully at android?

**Comment by tiendung01023** [comment]
@azhezzzz I fixed it in v0.0.8, thank for your support <3
