### ISSUE TITLE
Cannot login when run the example project

### ISSUE THREAD

**Issue by vietlinhtspt** [tiendung01023/zalo_flutter#4]
I have tried your example project and the login function is not working any ways with a error:
` {error_name:Invalid Parameter,error_reason:,ref_doc:https://developers.zalo.me/docs/api/social-api/tham-khao/user-access-token-post-4316,error_description:Invalid Parameter,error:-1040}`

**Comment by tiendung01023** [comment]
I'm sorry about not check your issue. I updated SDK v4. You can check again. If it have error, please reopen this issues
