### ISSUE TITLE
Support method shareFeed

### ISSUE THREAD

**Issue by madara134** [tiendung01023/zalo_flutter#5]
Hi bạn. Hiện tại lib chưa hỗ trợ hàm shareFeed. thanks

**Comment by tiendung01023** [comment]
Chào bạn, xin lỗi bạn vì mình không check phần Issues này. Mình mới update lên SDK v4 thì chỉ có thể lấy token cho việc đăng nhập và lấy thông tin user được thôi, token này không dùng cho các API của OA được nên mình không hỗ trợ cho API này được á bạn. Bạn thông cảm nha
